use_frameworks!

platform :ios, '8.0'

target 'GMEnvirSwitch_Example' do
  pod 'GMEnvirSwitch', :path => '../'

  target 'GMEnvirSwitch_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
