#use_frameworks!
source 'http://code.ds.gome.com.cn/gitlab/zhanghui-ds5/PrivateRepo.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ioszhanghui/GMPublicRepo.git'


platform :ios, '9.0'

target 'GMEnvirSwitch_Example' do
  pod 'GMEnvirSwitch', :path => '../'

  target 'GMEnvirSwitch_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
